# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Iterative proportional fitting
#'
#' Use iterative proportional fitting to
#' adjust \code{m} so that it is consistent
#' with \code{rowsums} and \code{colsums}.
#' \code{rowsums} and \code{colsums} can
#' include \code{NA}s, which indicate that
#' the associated row/column is not constrained.
#'
#' \code{m} is assumed to have no NAs or
#' negative values. Zeros are OK.
#'
#' \code{rowsums} and \code{colsums} are assumed
#' to have no negative values. NAs and zeros
#' are OK.
#'
#' @param m A matrix of doubles (not necessarily square)
#' @param rowsums A vector of doubles.
#' @param colsums A vector of doubles.
#' @param max_iter Maximum number of iterations.
#' @param tolerance Maximum absolute difference
#' between supplied values for rowsums/colsums
#' and derived values.
#'
#' @return A matrix with the same dimensions as \code{m}.
#'
#' @noRd
ipf <- function(m, rowsums, colsums, max_iter, tolerance) {
    .Call(`_dpmsplit_ipf`, m, rowsums, colsums, max_iter, tolerance)
}

